### ISSUE TITLE
Avoid converting `openfermion` operator at each call of the forward pass

### ISSUE THREAD

**Issue by madagra** [pasqal-io/pyqtorch#13]
When measuring an operator coming from `openfermion`, the conversion to a PyQ operator is performed at each forward pass. For large operators, this constitutes a large performance bottleneck.

The code performing the conversion is here:

```python
def measure_openfermion(
    state: torch.Tensor, operator: Any, N_qubits: int, batch_size: int
) -> torch.Tensor:
    new_state: torch.Tensor = torch.zeros_like(state)
    
    # FIXME: This can be cached and the operator matrix computed only once
    for op, coef in operator.terms.items():
        for qubit, pauli in op:
            state_bis = qubit_operators[pauli](state, [qubit], N_qubits)
            new_state += state_bis * coef

    state = state.reshape((2**N_qubits, batch_size))
    new_state = new_state.reshape((2**N_qubits, batch_size))

    return torch.real(torch.sum(torch.conj(state) * new_state, dim=0))
```

*Potential solution*: allow to cache the converted `openfermion` operator in the `QuantumCircuit` class and reuse the same matrix.

**Comment by manulpatel** [comment]
Hello! @madagra  I am new to PyQ and want to work on this issue.

**Comment by madagra** [comment]
> Hello! @madagra I am new to PyQ and want to work on this issue.

Hi @manulpatel . Please go ahead with the issue if you are still interested.

**Comment by manulpatel** [comment]
Sure! Will try to complete soon.
