### ISSUE TITLE
[Testing] Improve projector tests

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/pyqtorch#133]
Improvements to the test by generalising over arbitrary qubit numbers:

@[minikandreasseitz](https://github.com/dominikandreasseitz) [3 days ago](https://github.com/pasqal-io/pyqtorch/pull/131#discussion_r1404177927)
can we have tests with arbitary qubit numbers? maybe just pick random n_qubits and random qubits and apply the projector. there should be many tests like this in this very file

@[jpmoutinho](https://github.com/jpmoutinho) jpmoutinho [18 minutes ago](https://github.com/pasqal-io/pyqtorch/pull/131#discussion_r1406162753)
A possible extension to random states is to use the overlap and check that the overlap with a given product state used in the projector is the same before and after projection. Additionally the overlap with any other product state should be 0.

**Comment by chMoussa** [comment]
Closes as already implemented in #203
