### ISSUE TITLE
[Feature] Prototype for composite operations

### ISSUE THREAD

**Issue by Roland-djee** [pasqal-io/pyqtorch#167]
Rough prototype for a composite operation in PyQ to be used for circuits and hamiltonians.

- Currently it inherits from `ModuleList` but I don't know if this is ok in terms of general torch functionality, it just seemed to make sense that a a composite operation is just a container of smaller operations.
```
big_op = CompOp([X(0), X(1)])  # Composite operation equivalent to X on 2 qubits
big_op(product_state("00"))  # You get "11"
```
- The `AddOp` is pretty similar but the forward method sums the application of each block instead of applying it in sequence. It also allows a dict of modules in the case we want to parameterize a coefficient multiplying each term.
```
obs = AddOp({"a": Z(0), "b": Z(1)})
obs(product_state("00"), values = {"a": 1.0, "b": 1.0})  # Essentially applies Z_0 + Z_1
```
- The `Hamiltonian` uses both to construct a sum of composite operations so you can build Pauli Hamiltonians. Currently all it does on top of `AddOp` is to comprehend a nested structure:
```
obs = Hamiltonian({"a": [Z(0), Z(1)], "b": [X(0), X(1)]})
obs(product_state("00"), values = {"a": 2.0, "b": 1.0})  # Essentially applies 2*Z_0Z_1 + X_0X_1
```
- The goal would be to maybe have the `QuantumCircuit` also be just a thin wrapper on top of `CompOp`, since it should also just be a sequence of operations.

In the current state the tests pass locally, but not on github.

**Comment by jpmoutinho** [comment]
Closing since completed by @dominikandreasseitz
