### ISSUE TITLE
[Bug] Density_mat and torch.kron

### ISSUE THREAD

**Issue by EthanObadia** [pasqal-io/pyqtorch#168]
When I try to execute this lines:
```python
rho_0 = density_mat(product_state('0'))
promote_operator(rho_0,0,2)
```
The output is:
```python
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```
But if I execute these lines, which are completely equivalent, I don’t get any errors:
```python
rho_0 = DensityMatrix(pyq.Projector(1,'0','0').unitary())
promote_operator(rho_0,0,2)
```
I know this error comes from the function `torch.kron()` because `torch.kron(rho_0.contiguous(),I(0).unitary())` leads to the same error. 

Also, I already had the same error message when i tried to execute:
```python
torch.kron(I(0).dagger(),I(0).unitary())
```
According to this [tread](https://github.com/pytorch/pytorch/issues/54135), add `.contiguous()` resolved the problem, but this time the `permutation` does by `density_mat` is not a `transpose` and even with `.contiguous()` the problem is still there...

**Comment by Roland-djee** [comment]
@EthanObadia do you want to take that on ?

**Comment by EthanObadia** [comment]
For the moment I can't find the solution. So I'm going to think about it again and if I really can't find it I'll ask for help.

**Comment by Roland-djee** [comment]
> For the moment I can't find the solution. So I'm going to think about it again and if I really can't find it I'll ask for help.

OK. Assigning it to you. Feel free to nudge @dominikandreasseitz if you're stuck.

**Comment by EthanObadia** [comment]
I didn't find the solution yet, but i found that this code is working :
```python3
from pyqtorch.utils import random_state, product_state

n_qubits = 3
state_0, state_random = product_state('0'), random_state(n_qubits-1)
dm_0, dm_random = density_mat(state_0), density_mat(state_random)
dm_tot = torch.kron(dm_0,dm_random) #is working even without .contiguous()
```
Thus the bug is specific to `torch.kron(rho_0.contiguous(),I(0).unitary())`.
That's mean **the problem is when we use two different types as input in `torch.kron` including a use of `density_mat()`** because `dm_tot = torch.kron(dm_0,state_0)` is not working too.

**Comment by EthanObadia** [comment]
Finally, the error was related to the shape of the operators. The implementation of this function will resolve this bug:
```python3
def operator_kron(op1: Tensor, op2: Tensor) -> Tensor:
    """
    Compute the Kronecker product of two operators.

    This helps prevent errors related to the shape of the operators 
    [2**n_qubits, 2**n_qubits, batch_size] when simply using `torch.kron()`.
    Use of `.contiguous()` to avoid errors related to the `torch.kron()` of a transposing tensor

    Args:
        op1 (Tensor): The first input tensor.
        op2 (Tensor): The second input tensor.

    Returns:
        Tensor: The resulting tensor after applying the Kronecker product.

    """
    return batch_last(torch.kron(batch_first(op1).contiguous(), batch_first(op2).contiguous()))
