### ISSUE TITLE
[Feature] Port block_to_tensor to pyqtorch

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/pyqtorch#181]
Move the functionality of https://github.com/pasqal-io/qadence/blob/main/qadence/blocks/block_to_tensor.py which is used within the `qadence` version of HamiltonianEvolution ( https://github.com/pasqal-io/qadence/blob/main/qadence/backends/pyqtorch/convert_ops.py#L291) to instantiate a parametric hamiltonian from a abstract description.

**Comment by chMoussa** [comment]
@dominikandreasseitz I think this is already done with the current `tensor` method of `HamiltonianEvolution`, right? https://github.com/pasqal-io/pyqtorch/blob/5ead91791211b6fbd397ca32b19ab6a57638a713/pyqtorch/analog.py#L623

**Comment by dominikandreasseitz** [comment]
closing since completed
