### ISSUE TITLE
[Bug] Dimension Mismatch in promote_operator

### ISSUE THREAD

**Issue by EthanObadia** [pasqal-io/pyqtorch#183]
The `promote_operator` function does not correctly handle the promotion of operators acting on more than one qubit, such as 2-qubit gates. 

The current implementation of the `qubits` variable cannot accommodate gates with multiple targets, like the `SWAP` gate, or gates with a control qubit. This causes the promotion to incorrectly compute on qubit subspaces even if the gate is already defined on that qubit space, leading to dimension mismatches. 

Consequently, this issue results in runtime errors during tensor operations, particularly in the `torch.einsum` function.

EDIT by @jpmoutinho: The new `expand_operator` function should take care of this. Keeping this open until it is fully solved on main.

**Comment by Roland-djee** [comment]
@EthanObadia Is this still relevant ?

**Comment by EthanObadia** [comment]
> @EthanObadia Is this still relevant ?

Yes, it is still relevant. When extending the study of noise to multi-qubit gates this issue will be the starting point.
