### ISSUE TITLE
[Refact, Breaking] Listing important things to fix in PyQ

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/pyqtorch#225]
Currently we are at a state where we are migrating a lot of functionality to PyQ. To do that it is very important that we thoroughly review and improve all the base logic and guarantee that it is robustly defined and tested before we expand too much in features building on top of that. In this issue we list points that need to be addressed order in terms of how fundamental they are (e.g., how many other things build on top of that). For each one, we can open separate issues with more details and solutions.

- Most consistent qubit support logic / interface for all operators. Currently there are inconsistent uses of control / target arguments. How do we deal with the optional `control` argument?
- Minor conceptual thing, but the `pauli` argument in `Primitive` should just be called `matrix`.
- More robust and better tested `tensor` method working for primitive gates, noisy gates, and composite operations (related issues #210, #221).
- Logic of scale and observables (related issues #192) -- Already partially fixed here: https://github.com/pasqal-io/pyqtorch/pull/201, but requires adding more tests which depends on polishing the `tensor` method.
- Diagonal operators handling (related issues #211) -- Depends on having a more polished `tensor` method. We should probably have a `diag = True / False` in all `Primitives` and have a `apply_diag_operator` that never uses the full gate matrix, and a `tensor(..., diag = True)` that only returns the diagonal vector.
- Function for eigenvalues of generator for custom user-defined operators.
- Remove `unitary` method and keep only the `tensor` method?

**Comment by dominikandreasseitz** [comment]
- control qubit handling: i would strongly recommend replicating what [horqrux does](https://github.com/pasqal-io/horqrux/blob/main/horqrux/primitive.py#L91)
- rename to 'matrix': sure!
- Tensor method: yes, fully agreed and pointed out by myself many times. the `tensor` method is not well-tested yet and there is some significant work to be done to ensure it reliable
- logic of scale and observables: sure, that would be more consistent. i am however indifferent 
- diagonal observable merge into Observable: great! just didnt have time myself yet to do so
- eigenvals handling: great!
- remove unitary: i would keep only one of them and i guess tensor makes more sense
