### ISSUE TITLE
[Feature] Add Serialization for `QuantumCircuit` and `Embedding`

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/pyqtorch#231]
cc @Roland-djee 

Possible options:

1. JSON (like qadence) or https://pytorch.org/docs/stable/notes/serialization.html for QuantumCircuit
2. tensordict serialization for Embedding https://pytorch.org/docs/stable/notes/serialization.html

**Comment by jpmoutinho** [comment]
To note that @vytautas-a is currently reviewing the embedding in https://github.com/pasqal-io/pyqtorch/pull/228, changes may come from it.

**Comment by mlahariya** [comment]
Not relevant for now. @RolandMacDoland  - can you please let us know if this is needed/priority? if not, we can close this.

**Comment by RolandMacDoland** [comment]
> Not relevant for now. @RolandMacDoland - can you please let us know if this is needed/priority? if not, we can close this.

I don't think so now. Serialisation is likely to happen elsewhere (Qadence) I assume. We can re-open if there is a need.
