### ISSUE TITLE
[Feature] GPSR and Hamevo compatibility

### ISSUE THREAD

**Issue by chMoussa** [pasqal-io/pyqtorch#238]
Check/Make Hamevo compatible with GPSR and add tests

**Comment by jpmoutinho** [comment]
Some relevant Qadence issues:
https://github.com/pasqal-io/qadence/issues/266
https://github.com/pasqal-io/qadence/issues/397

**Comment by rajaiitp** [comment]
I will point out a usecase where gpsr is not supposed to work, just so that its not something you try to work with. 
$$ H =  \alpha X  + Z  $$

Gpsr will not give the derivative wrt to \alpha for hamevo(H), because it does not scale the full generator of the unitary it is a part of.

**Comment by jpmoutinho** [comment]
Yes @rajaiitp this was my point that GPSR assumes something like $G.x$ while in the code we allow generators with an arbitrary dependence $G(x)$ to be written.
