### ISSUE TITLE
[Refact] More consistent and robust Primitive and Parametric classes

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/pyqtorch#240]
The `Primitive` and `Parametric` classes are the root of most operations in PyQ. Currently, there are a few things that could be polished about them:

- `Primitive` has a `pauli` and `target` argument, but the way the class works is more general, as it applies any `matrix` to a given `qubit_support`. The argument names should reflect that.
- On that note, `Primitive` does not error out if there is dimension mismatch between the matrix and the support, e.g. a 2-qubit matrix to be applied to a 1-qubit support. Instead, it will then error out in the `forward` method. It would be safe to enforce this at initialization. When I tried this, I ran into another problem...
- The `Parametric` class inherits from `Primitive` but has a different interface and behaviour. It instantiates the parent class with the matrix of the "generator" of the rotation.
- The behaviour of the `ControlledRotationGate` is where the inconsistency arises, since it initializes the `Parametric` and hence the `Primitive` again with the matrix of the generator, but not the "larger" matrix of the controlled-rotation, because that one is only created in the `forward` method so that it is updated with the values of the rotation. In contrast, the `ControlledOperationGate` create the "larger" matrix at initialization, and hence it initializes the `Primitive` already with the controlled-matrix. What this means is that with the current logic the `ControlledRotationGate` will always instantiate a `Primitive` with a mismatch between the matrix size and the actual support of the operation.
- Simplify the `qubit_support` as a `@property` [[link]](https://github.com/pasqal-io/pyqtorch/pull/220#discussion_r1692891377).
- Remove unitary method and keep only the tensor method?

Given the importance of these classes, we should think a bit about this and come up with a more robust and consistent design.

**Comment by chMoussa** [comment]
Closing with #246
