### ISSUE TITLE
[Refact] Optimize `permute_basis` function

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/pyqtorch#241]
The goal of the `permute_basis` function is to permute the rows and columns of a given operator matrix according to a permutation on the qubit support that is different than `tuple(range(n_qubits))`. E.g., the matrix for `CNOT(0, 1)` is
```
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]], dtype=torch.float64)
```
but the one for `CNOT(1, 0)` should be
```
tensor([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 1., 0., 0.]], dtype=torch.float64)
```
Currently this permutation is generated by explicitly writing down all the basis states in bitstring format, permuting the position of all qubits according to the qubit support order, and then rebuilding the integer values using the different order of the basis states, which gives the correct basis state permutation that can be used to slice the operator with. This is handled by the `_basis_order` function in `pyqtorch.bitstrings`.

As @chMoussa pointed out [here](https://github.com/pasqal-io/pyqtorch/pull/220#discussion_r1689394629), there is probably a smarter way of doing it with `torch.permute`. This requires viewing the operator with a similar shape to what is done in the function `apply_operator`, then permuting the dimensions of the tensor according to the qubit support, and then reshaping back. Below is a trial code to do that:

```
def new_permute(operator: torch.Tensor, qubit_support: tuple[int, ...]) -> torch.Tensor:
    n_qubits = len(qubit_support)
    batch_size = operator.size(-1)
    operator = operator.view([2] * 2 * n_qubits + [batch_size])
    perm = list(qubit_support + tuple(n_qubits + q for q in qubit_support) + (2*n_qubits,))
    return operator.permute(perm).reshape([2**n_qubits, 2**n_qubits, batch_size])
```

This *almost* does it, but it is still not fully working. For example, see the code below:

```
import torch
import random
from pyqtorch.bitstrings import permute_basis

n_qubits = 3
operator = torch.randint(2, (2**n_qubits, 2**n_qubits)).unsqueeze(2)

def new_permute(operator, qubit_support):
    n_qubits = len(qubit_support)
    batch_size = operator.size(-1)
    operator = operator.view([2] * 2 * n_qubits + [batch_size])
    perm = list(qubit_support + tuple(n_qubits + q for q in qubit_support) + (2*n_qubits,))
    return operator.permute(perm).reshape([2**n_qubits, 2**n_qubits, batch_size])

qubit_support = (0, 1, 2)  # Works, no permutation is done ofc
qubit_support = (0, 2, 1)  # Also works
qubit_support = (1, 0, 2)  # Also works
qubit_support = (2, 1, 0)  # Also works
qubit_support = (2, 0, 1)  # Does not work

op_perm_0 = permute_basis(operator, qubit_support)
op_perm_1 = new_permute(operator, qubit_support)

torch.allclose(op_perm_0, op_perm_1)
```

**Comment by chMoussa** [comment]
Closing as solved with #242
