### ISSUE TITLE
[Bug] Ninja error in the `HamiltonianEvolution` with parametric generator

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/pyqtorch#280]
### Short description

I've seen the pipeline failing a few times with this error:

<img width="1379" alt="image" src="https://github.com/user-attachments/assets/5a1c9261-be6c-4496-86a4-a78c66d852f3">

But it doesn't happen all the time. The generator used there is generated randomly from the function `tests.helpers.random_pauli_hamiltonian`, so I guess sometimes one generator triggers the error and sometimes it doesn't. I suspect this relates to the removal of the parametric generator boolean flag and the introduction of the `is_parametric` function, but I have not traced it yet.

### Steps/Code to reproduce

Currently unavailable

### Would you like to work on this issue?

None

**Comment by vytautas-a** [comment]
ok, that's interesting - I'll take look

**Comment by jpmoutinho** [comment]
Ok I found the issue, it was just that the `random_pauli_hamiltonian` function had a probability to give an unparameterized Hamiltonian even if it was told to give a parameterized one. It's fixed now.
