### ISSUE TITLE
[Performance] Investigate the performance of `is_diag` function

### ISSUE THREAD

**Issue by vytautas-a** [pasqal-io/pyqtorch#283]
Investigate the performance of `is_diag` function implementations when off-diagonal are computed with
```
m = H.shape[0]
p, q = H.stride()
offdiag_view = torch.as_strided(H[:, 1:], (m - 1, m), (p + q, q))
```
or 
```
offdiag_view = H - torch.diag(torch.diag(H))
```
The first option fails with latest PR's from `qadence` (https://github.com/pasqal-io/qadence/pull/568) and `pyqtorch` (https://github.com/pasqal-io/pyqtorch/pull/275).

**Comment by chMoussa** [comment]
The first option is actually faster @vytautas-a , times for a 10k square matrix are:

With `offdiag_view = H - torch.diag(torch.diag(H))`
CPU times: user 358 ms, sys: 487 ms, total: 845 ms
Wall time: 102 ms

vs using the strided view

CPU times: user 192 ms, sys: 215 ms, total: 406 ms
Wall time: 49.2 ms

**Comment by vytautas-a** [comment]
> The first option is actually faster @vytautas-a , times for a 10k square matrix are:
> 
> With `offdiag_view = H - torch.diag(torch.diag(H))` CPU times: user 358 ms, sys: 487 ms, total: 845 ms Wall time: 102 ms
> 
> vs using the strided view
> 
> CPU times: user 192 ms, sys: 215 ms, total: 406 ms Wall time: 49.2 ms

I see. That means we have to find out why is the first option failing with this particular test:
```
FAILED tests/qadence/test_quantum_model.py::test_quantum_model_with_hevo - RuntimeError: setStorage: sizes [15, 16], strides [17, 16], storage offset 2320, and itemsize 8 requiring a storage size of 22392 are out of bounds for storage of size 20480
```

**Comment by chMoussa** [comment]
@vytautas-a I tried many ways but your solution is the best so far. The problem is inherent to the `as_strided` function which can cover many cases but cases with multiple indices referring to the same element in memory can throw such error and that's non trivial to me. I think your solution is good enough, and won't break any computational graph.
