### ISSUE TITLE
Add constructors like HEA to modules

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/pyqtorch#37]
**Update for clarity: This issue is about the Module API.**
The basis of many differentiable quantum models is the hardware efficient ansatz (HEA), implemented as a series of single qubit rotations followed by a layer of controlled operations for entanglement. Implement a generic constructor method that initializes a HEA for a given number of qubits and a certain number of layers (depth of the HEA).

**Comment by neogyk** [comment]
Hey, I would like to work on this issue:)

**Comment by dominikandreasseitz** [comment]
Hi @neogyk , welcome and have fun with the issue!

**Comment by dominikandreasseitz** [comment]
hi @neogyk, is there an update on this? are you planning to submit an MR?

**Comment by dominikandreasseitz** [comment]
can be closed since related to #102
