### ISSUE TITLE
[Feature] Add wavefunction normalization check

### ISSUE THREAD

**Issue by jpmoutinho** [pasqal-io/pyqtorch#56]
Certain numerical operations like the Hamiltonian Evolution with RK4 method do not conserve the wavefunction normalization. We should either:
- Add a normalization check at certain steps in the computation and raise an error when above certain threshold.
- Add a renormalization step to any non-norm-conserving operations (the danger being that the results will diverge without raising any errors).

Implement both of the above solutions with a flag for choosing which one to use when building the quantum circuit.

**Comment by ducthanh1991** [comment]
Hello @jpmoutinho, is this issue still open?

**Comment by jpmoutinho** [comment]
Hi @ducthanh1991, actually for now I would say this issue is not relevant since the code it related to is not there anymore. It will possibly become relevant again soon since we are in the process of adding a some new methods for solving the Schrodinger equation.
