### ISSUE TITLE
[Testing] Add unit tests which check pre-computed analytical expression

### ISSUE THREAD

**Issue by dominikandreasseitz** [pasqal-io/pyqtorch#60]
**Update for clarity: This issue is about the Module API.**
Come up with simple circuits, compute the expected result analytically and check if the result matches.

1. The first testfile should include (combinations of) pauli gates, rotation gates, controlled gates, the U-gate, etc.

### Example
```python
assert X(zero_state(n_qubits=1)) == one_state(n_qubits=1)
```
2. The second testfile should be about convergence tests using a simple QuantumCircuit which you will fit on a simple sine.

To complete this issue at least one test per existing gate should be written.

**Comment by abrassel** [comment]
Hi, I'd like to work on this issue! Can you assign me as an owner?

**Comment by dominikandreasseitz** [comment]
Hey, welcome to Pyq and thanks for participating! yes, i can do that

**Comment by s-aldaihan** [comment]
I am also interested in this issue if still open for contributions @dominikandreasseitz

**Comment by dominikandreasseitz** [comment]
hi @s-aldaihan , of course we would be happy if you contributed more unit tests to PyQ. the issue/ potential reward is however already assigned to @abrassel. so i can either offer you (1) to contribute without a monetary reward (2) ask @abrassel if he is actually working on the issue/plans to submit an MR, if not, let me know

**Comment by s-aldaihan** [comment]
Thanks @dominikandreasseitz.  
@abrassel Can you please let me know if you are still considering contributing to this issue?

**Comment by abrassel** [comment]
Hi! I am still planning on working on this. Typically I don't mind collaborating, but this particular issue seems pretty small.  I'm not sure if there's a meaningful amount of collaboration to do

**Comment by s-aldaihan** [comment]
@abrassel Sure!
@dominikandreasseitz I would like to contribute without the monetary reward, if possible

**Comment by dominikandreasseitz** [comment]
great, so please coordinate with eachother then :) thanks @s-aldaihan ! and i dont think its a small issue ;) try thinking about edge cases! try to include every gate we have etc

**Comment by abrassel** [comment]
It's ok @s-aldaihan feel free to do. I'll go find another issue to work on :)

**Comment by dominikandreasseitz** [comment]
hey! hows it going here @abrassel @s-aldaihan

**Comment by abrassel** [comment]
Hi! As I mentioned earlier, I didn't want to compete on this project :)

**Comment by dominikandreasseitz** [comment]
oh ok sorry! my understanding was that you are collaborating, but i understand of course!

**Comment by dominikandreasseitz** [comment]
hi @s-aldaihan, are you working on this issue? if yes, i would assign you. otherwise i would ask someone else do it :) let me know please!
