### ISSUE TITLE
Add method: QuantumCircuit.matrices

### ISSUE THREAD

**Issue by nmheim** [pasqal-io/pyqtorch#71]
Implement `QuantumCircuit.matrices` similar to the gates. we have to take care to properly, multiply/kron the operations of a circuit. As these matrices can become very large we should make use of `torch.sparse`. This means that we likely have to refactor all `.matrices` methods to at least have the option of outputting a sparse matrix.

**Comment by dominikandreasseitz** [comment]
very nice!

**Comment by dominikandreasseitz** [comment]
not sure if this makes sense anymore, wdyt @nmheim ?

**Comment by nmheim** [comment]
`.matrices` is now called `.unitary` right?
