### ISSUE TITLE
`HamiltonianEvolution` refactor

### ISSUE THREAD

**Issue by nmheim** [pasqal-io/pyqtorch#84]
I thought this was going to be addressed in #69 but can we get one class that computes the hamiltonian evolution and then just calls three different functions like `hamevo_exp(H, t, ...)`?

The three classes that are wrapped by `HamiltonianEvolution` are not necessary, because they are reconstructed with every call to `HamiltonianEvolution.forward`, so they could just be functions.

Additionally, more robust tests would be really great.

@jpmoutinho if you want to take this on feel free to assign yourself (and add whatever else you think would be good to have from a refactor) :)

**Comment by dominikandreasseitz** [comment]
done in the remake, feel free to check @nmheim
